<?php
/**
 * @file
 * Watchdog js errors module.
 */

/**
 * Implements hook_menu().
 */
function watchdog_js_errors_menu() {
  return array(
    'watchdog_js_errors' => array(
      'page callback' => 'watchdog_js_errors_callback',
      'access callback' => TRUE,
      'delivery callback' => 'drupal_json_output',
    ),
  );
}

/**
 * Page callback.
 */
function watchdog_js_errors_callback() {
  if (user_access('save_watchdog_js_errors')) {
    $errors = $_POST['errors'];
    foreach ($errors as $error) {
      watchdog('watchdog_js_errors', 'Error :message in line :line', array(':message' => $error['message'], ':line' => $error['line']), WATCHDOG_ERROR, $error['url']);
    }

    return t('Saved in Watchdog!');
  }
}

/**
 * Implements hook_permission().
 */
function watchdog_js_errors_permission() {
  return array(
    'save_watchdog_js_errors' => array(
      'title' => t('Save js errors in Watchdog'),
      'description' => t('Allows users to save js errors in watchdog.'),
    ),
  );
}

/**
 * Implements hook_init().
 */
function watchdog_js_errors_init() {
  if (user_access('save_watchdog_js_errors')) {
    $module_path = drupal_get_path('module', 'watchdog_js_errors');
    drupal_add_js($module_path . '/js/watchdog_js_errors.js');
  }
}
