<?php

/**
 * Implements hook_menu().
 */
function watchdog_js_errors_menu() {
  return array(
    'watchdog_js_errors' => array(
      'page callback' => 'watchdog_js_errors_callback',
      'access callback' => TRUE,
      'delivery callback' => 'drupal_json_output',
    ),
  );
}

/**
 * Page callback.
 */
function watchdog_js_errors_callback() {
  $errors = $_POST['errors'];
  foreach ($errors as $error) {
    watchdog('watchdog_js_errors', 'Error :message in line :line', array(':message' => $error['message'], ':line' => $error['line']), WATCHDOG_ERROR, $error['url']);
  }

  return t('Saved in Watchdog!');
}
